### ISSUE TITLE
Mix https z http

### ISSUE THREAD

**Issue by Yimmir** [Yimmir/CodersCamp2020.JS-MajaTEAM#13]
**Opisz błąd**
Appka poprzez github pages jest uruchamiana za pomocą https, a odwołanie do api jest przez http.
Wskutek tego następuje blokada treści poprzez html i request nie zostaje zwrócony.
**Środowisko*
github-pages deployment

**Kroki do reprodukcji**
Wybierz dowolny tryb,
Uruchom quiz

**Console Log**
```Mixed Content: The page at 'https://yimmir.github.io/CodersCamp2020.JS-MajaTEAM/' was loaded over HTTPS, but requested an insecure resource 'http://swapi.dev/api/vehicles/37/'. This request has been blocked; the content must be served over HTTPS.```

**Comment by marlexxa** [comment]
Zostały dodane meta informację, które traktują zapytania z api jako bezpieczne. 
Commit: [ee89a27](https://github.com/Yimmir/CodersCamp2020.JS-MajaTEAM/commit/ee89a278079df0e3e8ba2155eedadea5ea493812)
