### ISSUE TITLE
Bład wyboru kategorii

### ISSUE THREAD

**Issue by Arvanes** [Yimmir/CodersCamp2020.JS-MajaTEAM#9]
**Opisz błąd**
Po wyborze kategorii a następnie zmiany na kolejną, style nie są przywracane do wcześniej wybranej kategorii.

**Kroki do reprodukcji**
1. Wybór kategorii People
2. Wybór kategorii Vehicles

**Screenshoty**
![Zrzut ekranu z 2021-01-15 13-36-55](https://user-images.githubusercontent.com/26483159/104728343-0e51ed00-5737-11eb-8acf-79f0f66ba93d.png)

**Comment by Arvanes** [comment]
Powinno działać w takiej postaci
```    
for (let i = 0; i < modes.length; i++) {
        modes[i].addEventListener('click', () => {
            for (let j = 0; j < modes.length; j++) {
                modes[j].classList.remove('modeEnabled');
            }
         //   modes[i].classList.remove('modeDisabled'); // niepotrzebna linijka
            modes[i].classList.add('modeEnabled');
        })
    }
```

**Comment by Yimmir** [comment]
Zrobiłem to trochę na odwrót, wszystkie klasy najpierw tracą mode Enabled a potem dostają modeDisabled. Twoja opcja w sumie też dobra, bo Enabled jest wyżej (plus można dodać !important też).
Zrobione tym commitem: 04d8ec0e4b4fd3e4e2441b1f297cb5d6abb9884b
